In [7]:
%pip install pandas
%pip install matplotlib
%pip install numpy

Requirement already satisfied: pandas in c:\users\maryh\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\maryh\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in c:\users\maryh\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\maryh\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\maryh\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in c:\users\maryh\anaconda3\lib\site-packages (3.5.2)
Requirement already satisfied: numpy>=1.17 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: packaging>=20.0 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (1.4.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\maryh\anaconda3\lib\site-packages (from matplotlib) (9.2.0)
Requirement already satisfied: six>=1.5 in c:\users\maryh\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\maryh\anaconda3\lib\site-packages (1.21.5)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

plt.rcParams['figure.figsize'] = (15, 15)

dados = pd.read_csv('../Arquivo/trabalho2_dados_grupo-08.csv', index_col="Name")

In [9]:
dados #dados da forma de como veio

,Candidate ID,Number of characters in Original Name,Month of Birth,Year of Birth,Gender,State (Location),10th percentage,12th percentage,10th Completion Year,12th Completion year,...,Quantitative Ability 3,Quantitative Ability 4,Domain Skills 1,Domain Skills 2,Domain Test 3,Domain Test 4,Analytical Skills 1,Analytical Skills 2,Analytical Skills 3,Performance
Name,,,,,,,,,,,,,,,,,,,,,
PtS,1131,13,FEB,Y7,A,N,83.80,84.00,Y13,Y15,...,65.363128,63.005780,48.2142857142857,68.345324,68.275862,59.124088,90.9090909090909,81.012658,95.402299,BP
AyS,130,11,NOV,Y7,B,D,84.40,77.00,Y14,Y16,...,56.424581,65.317919,50,66.906475,68.275862,60.583942,67.2727272727273,88.607595,56.321839,BP
CiK,882,13,MAR,Y8,B,N,86.26,62.83,Y14,Y16,...,50.837989,52.601156,46.4285714285714,56.834532,72.413793,64.963504,60,79.746835,32.183908,BP
AhS,28,12,MAR,Y8,A,F,81.00,72.00,Y14,Y16,...,55.307263,56.069364,35.7142857142857,53.956835,71.034483,50.364964,47.2727272727273,73.417722,35.632184,BP
MnV,239,25,NOV,Y7,A,E,62.92,68.00,Y14,Y16,...,38.547486,61.849711,19.6428571428571,39.568345,43.448276,62.043796,45.4545454545455,60.759494,40.229885,BP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AlY,1210,11,SEP,Y7,A,T,67.00,75.60,Y14,Y16,...,70.949721,69.942197,67.8571428571429,81.294964,68.275862,82.481752,78.1818181818182,68.354430,81.609195,LP
BaS,1268,21,JAN,Y3,A,E,83.20,83.33,Y10,Y12,...,69.832402,60.693642,51.7857142857143,56.834532,80.689655,66.423358,67.2727272727273,73.417722,63.218391,MP
AhR,229,8,NOV,Y7,A,D,82.20,81.20,Y14,Y16,...,73.184358,67.630058,58.9285714285714,82.733813,58.620690,70.802920,40,50.632911,35.632184,BP
SiR,1181,9,JUN,Y8,B,A,89.45,96.25,Y14,Y16,...,75.418994,67.630058,48.2142857142857,59.712230,64.137931,78.102190,76.3636363636364,68.354430,81.609195,BP
ShS,1126,12,NOV,Y6,B,M,86.20,80.40,Y13,Y15,...,43.016760,66.473988,26.7857142857143,58.273381,36.551724,51.824818,70.9090909090909,60.759494,77.011494,BP

In [10]:
for column in dados.columns:
    print("'" + column + "'", " - ", type(column))

'Candidate ID'  -  <class 'str'>
'Number of characters in Original Name'  -  <class 'str'>
'Month of Birth'  -  <class 'str'>
'Year of Birth'  -  <class 'str'>
'Gender'  -  <class 'str'>
'State (Location)'  -  <class 'str'>
' 10th percentage'  -  <class 'str'>
' 12th percentage'  -  <class 'str'>
'10th Completion Year'  -  <class 'str'>
'12th Completion year'  -  <class 'str'>
'Degree of study'  -  <class 'str'>
'Specialization in study'  -  <class 'str'>
' College percentage'  -  <class 'str'>
' Year of Completion of college'  -  <class 'str'>
' English 1'  -  <class 'str'>
'English 2'  -  <class 'str'>
'English 3'  -  <class 'str'>
'English 4'  -  <class 'str'>
'Quantitative Ability 1'  -  <class 'str'>
'Quantitative Ability 2'  -  <class 'str'>
'Quantitative Ability 3'  -  <class 'str'>
'Quantitative Ability 4'  -  <class 'str'>
'Domain Skills 1'  -  <class 'str'>
'Domain Skills 2'  -  <class 'str'>
'Domain Test 3'  -  <class 'str'>
'Domain Test 4'  -  <class 'str'>
'Analytical Skills 1'  -  <class 'str'>
'Analytical Skills 2'  -  <class 'str'>
'Analytical Skills 3'  -  <class 'str'>
'Performance'  -  <class 'str'>